import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from '@react-pdf/renderer'
import type { Slide } from './prompt'
import {
  RobotoRegular,
  RobotoBold,
  RobotoRegularItalic,
} from './fonts/robotoWoffBase64'

// Nhúng base64: fetch từ URL (/fonts/...) gây "Unknown font format" trong @react-pdf.
// Font nguồn vẫn ở public/fonts; file TS này generate bằng: node scripts/embed-fonts.cjs
const dataUrl = (b64: string) => `data:font/woff;base64,${b64}`
Font.register({
  family: 'Roboto',
  fonts: [
    { src: dataUrl(RobotoRegular) },
    { src: dataUrl(RobotoBold), fontWeight: 'bold' },
    { src: dataUrl(RobotoRegularItalic), fontStyle: 'italic' },
  ],
})

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Roboto',
    fontSize: 10,
    backgroundColor: '#FFFFFF',
    lineHeight: 1.6,
  },
  header: {
    fontSize: 20,
    marginBottom: 8,
    fontWeight: 'bold',
    color: '#1a1a1a',
    letterSpacing: 0.5,
  },
  subHeader: {
    fontSize: 9,
    color: '#666666',
    marginBottom: 24,
    fontStyle: 'italic',
  },
  table: {
    display: 'flex',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#d0d0d0',
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderRadius: 4,
  },
  tableRow: {
    margin: 'auto',
    flexDirection: 'row',
  },
  tableColHeader: {
    width: '38%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderColor: '#d0d0d0',
    backgroundColor: '#2c3e50',
    padding: 10,
  },
  tableColHeader2: {
    width: '62%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderColor: '#d0d0d0',
    backgroundColor: '#2c3e50',
    padding: 10,
  },
  tableCol: {
    width: '38%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderColor: '#d0d0d0',
    padding: 12,
    backgroundColor: '#fafafa',
  },
  tableCol2: {
    width: '62%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderColor: '#d0d0d0',
    padding: 12,
    backgroundColor: '#ffffff',
  },
  tableCellHeader: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 10,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  slideTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 6,
    lineHeight: 1.4,
  },
  tableCell: {
    fontSize: 10,
    marginBottom: 4,
    lineHeight: 1.7,
    color: '#2d2d2d',
  },
  metaLabel: {
    color: '#7f8c8d',
    fontSize: 8.5,
    marginTop: 6,
    marginBottom: 2,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  metaValue: {
    color: '#95a5a6',
    fontSize: 8,
    marginBottom: 3,
  },
  visualLabel: {
    color: '#34495e',
    fontSize: 9,
    marginTop: 10,
    marginBottom: 4,
    fontWeight: 'bold',
  },
  visualText: {
    fontSize: 9.5,
    lineHeight: 1.6,
    color: '#4a4a4a',
  },
  speakerNotesLabel: {
    color: '#8e44ad',
    fontSize: 9,
    marginTop: 10,
    marginBottom: 4,
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
  speakerNotesText: {
    fontSize: 9.5,
    lineHeight: 1.6,
    color: '#555555',
    fontStyle: 'italic',
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    right: 40,
    fontSize: 8,
    color: '#95a5a6',
  },
})

function cleanText(txt: string): string {
  return txt?.replace(/\*\*(.*?)\*\*/g, '$1').trim() ?? ''
}

export function ScriptPdfDocument({
  slides,
  filename,
}: {
  slides: Slide[]
  filename: string
}) {
  return (
    <Document title={filename} author="Vibriona">
      <Page size="A4" orientation="landscape" style={styles.page}>
        <Text style={styles.header}>{filename.replace(/_/g, ' ')}</Text>
        <Text style={styles.subHeader}>
          Generated by Vibriona — {new Date().toLocaleDateString()}
        </Text>

        <View style={styles.table}>
          <View style={styles.tableRow}>
            <View style={styles.tableColHeader}>
              <Text style={styles.tableCellHeader}>VISUALS</Text>
            </View>
            <View style={styles.tableColHeader2}>
              <Text style={styles.tableCellHeader}>AUDIO / SCRIPT</Text>
            </View>
          </View>

          {slides.map((slide, i) => (
            <View style={styles.tableRow} key={i}>
              <View style={styles.tableCol}>
                <Text style={styles.slideTitle}>
                  Slide {slide.slide_number}: {cleanText(slide.title)}
                </Text>

                {slide.layout_suggestion && (
                  <>
                    <Text style={styles.metaLabel}>Layout</Text>
                    <Text style={styles.metaValue}>{slide.layout_suggestion}</Text>
                  </>
                )}

                {slide.estimated_duration && (
                  <>
                    <Text style={styles.metaLabel}>Duration</Text>
                    <Text style={styles.metaValue}>{slide.estimated_duration}</Text>
                  </>
                )}

                {slide.visual_description && (
                  <>
                    <Text style={styles.visualLabel}>Visual Description</Text>
                    <Text style={styles.visualText}>
                      {cleanText(slide.visual_description)}
                    </Text>
                  </>
                )}
              </View>

              <View style={styles.tableCol2}>
                {slide.content && (
                  <Text style={styles.tableCell}>
                    {cleanText(slide.content)}
                  </Text>
                )}

                {slide.speaker_notes && (
                  <>
                    <Text style={styles.speakerNotesLabel}>
                      Speaker Notes
                    </Text>
                    <Text style={styles.speakerNotesText}>
                      {cleanText(slide.speaker_notes)}
                    </Text>
                  </>
                )}
              </View>
            </View>
          ))}
        </View>

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  )
}
